import { State } from '@/src/pages/game/Game.type.ts';

export const gameState: State = {
  cash: 0,
  creativity: 0,
  factory: 0,
  factoryCost: 1e5,
  feature: {
    factory: false,
    fundsPerSecond: false,
    investments: false,
    machine: false,
    marketing: false,
    megaMachine: false,
    production: false,
    resources: false,
    swarmGifts: false,
    swarmStrategy: false,
    trust: true,
    wire: true,
  },
  funds: 0,
  fundsPerSecond: 0,
  harvesterDrone: 0,
  harvesterDroneCost: 1e4,
  machine: 0,
  machineBonus: 1,
  machineCost: 5,
  machineRef: 0,
  marketing: 1,
  marketingBonus: 1,
  marketingCost: 100,
  megaMachine: 0,
  megaMachineCost: 5e2,
  memory: 1,
  operations: 0,
  operationsMax: 5e2,
  paperclip: 0,
  paperclipPrice: 0.2,
  paperclipPriceRef: 0.2,
  paperclipPerSecond: 0,
  processors: 1,
  projects: [
    {
      id: 'revTracker',
      enabled: false,
      unlocked: false,
      cost: 25,
    },
    {
      id: 'begForMoreWire',
      enabled: false,
      unlocked: false,
      cost: 250,
    },
    {
      id: 'improvedWireExtrusion',
      enabled: false,
      unlocked: false,
      cost: 500,
    },
    {
      id: 'optimizedWireframe',
      enabled: false,
      unlocked: false,
      cost: 1700,
    },
    {
      id: 'wireBuyer',
      enabled: false,
      unlocked: false,
      cost: 2000,
    },
    {
      id: 'algorithmicTrading',
      enabled: false,
      unlocked: false,
      cost: 3500,
    },
    {
      id: 'newSlogan',
      enabled: false,
      unlocked: false,
      cost: 7000,
    },
    {
      id: 'attractiveJingle',
      enabled: false,
      unlocked: false,
      cost: 7500,
    },
    {
      id: 'hypnoHarmonics',
      enabled: false,
      unlocked: false,
      cost: 10000,
    },
    {
      id: 'hostileTakeover',
      enabled: false,
      unlocked: false,
      cost: 15000,
    },
    {
      id: 'fullMonopoly',
      enabled: false,
      unlocked: false,
      cost: 20000,
    },
    {
      id: 'machinesImprovement',
      enabled: false,
      unlocked: false,
      cost: 25000,
    },
    {
      id: 'evenBetterMachines',
      enabled: false,
      unlocked: false,
      cost: 50000,
    },
    {
      id: 'hypnoticHarmonics',
      enabled: false,
      unlocked: false,
      cost: 70000,
    },
  ],
  publicDemand: 0.5,
  swarmGifts: 0,
  swarmStrategy: 5,
  trust: 2,
  unsoldInventory: 0,
  unsoldInventoryBonus: 1,
  wallet: {
    BTC: { quantity: 0 },
    ETH: { quantity: 0 },
    BNB: { quantity: 0 },
  },
  wire: 100,
  wireBonus: 100,
  wireCost: 20,
  wireDrone: 0,
  wireDroneCost: 1e4,
};
