import { State } from '@/src/pages/game/Game.type.ts';

export const gameState: State = {
  cash: 0,
  creativity: 0,
  feature: {
    machine: false,
    megaMachine: false,
    paperclipPerSecond: false,
    wire: true,
  },
  funds: 0,
  fundsPerSecond: 0,
  machine: 0,
  machineCost: 5,
  marketing: 1,
  marketingCost: 100,
  megaMachine: 0,
  megaMachineCost: 5e2,
  memory: 1,
  operation: 0,
  operationMax: 5e4,
  paperclip: 0,
  paperclipCost: 0.2,
  paperclipCostRef: 0.2,
  paperclipPerSecond: 0,
  publicDemand: 0.5,
  processor: 1,
  trust: 2,
  trustCost: 3e3,
  unsold: 0,
  unsoldBonus: 1,
  wallet: [
    { symbol: 'BTC', quantity: 0 },
    { symbol: 'ETH', quantity: 0 },
    { symbol: 'BNB', quantity: 0 },
  ],
  wire: 100,
  wireBonus: 100,
  wireCost: 20,
  wireDrone: 0,
  wireDroneCost: 1e4,
};
