import { State } from '@/src/pages/game/Game.type.ts';

export const gameState: State = {
  cash: 0,
  creativity: 0,
  factory: 0,
  factoryCost: 1e5,
  feature: {
    factory: true,
    fundsPerSecond: true,
    investments: true,
    machine: true,
    marketing: true,
    megaMachine: true,
    production: true,
    resources: true,
    trust: true, // true
    wire: true, // true
  },
  funds: 0,
  fundsPerSecond: 0,
  harvesterDrone: 0,
  harvesterDroneCost: 1e4,
  machine: 0,
  machineBonus: 1,
  machineCost: 5,
  machineRef: 0,
  marketing: 1,
  marketingCost: 100,
  megaMachine: 0,
  megaMachineCost: 5e2,
  memory: 1,
  operation: 0,
  operationMax: 5e4,
  paperclip: 0,
  paperclipPrice: 0.2,
  paperclipPriceRef: 0.2,
  paperclipPerSecond: 0,
  processor: 1,
  projects: [
    {
      id: 'revTracker',
      enabled: true,
      unlocked: true,
    },
    {
      id: 'begForMoreWire',
      enabled: true,
      unlocked: true,
    },
    {
      id: 'improvedWireExtrusion',
      enabled: true,
      unlocked: true,
    },
    {
      id: 'optimizedWireframe',
      enabled: true,
      unlocked: true,
    },
    {
      id: 'wireBuyer',
      enabled: true,
      unlocked: true,
    },
    {
      id: 'algorithmicTrading',
      enabled: true,
      unlocked: true,
    },
    {
      id: 'newSlogan',
      enabled: true,
      unlocked: true,
    },
    {
      id: 'attractiveJingle',
      enabled: true,
      unlocked: true,
    },
    {
      id: 'hypnoHarmonics',
      enabled: true,
      unlocked: true,
    },
    {
      id: 'hostileTakeover',
      enabled: true,
      unlocked: true,
    },
    {
      id: 'fullMonopoly',
      enabled: true,
      unlocked: true,
    },
    {
      id: 'machinesImprovement',
      enabled: true,
      unlocked: true,
    },
    {
      id: 'evenBetterMachines',
      enabled: true,
      unlocked: true,
    },
  ],
  publicDemand: 0.5,
  gifts: 0,
  thinking: 0,
  trust: 2,
  unsoldInventory: 0,
  unsoldInventoryBonus: 1,
  wallet: {
    BTC: { quantity: 0 },
    ETH: { quantity: 0 },
    BNB: { quantity: 0 },
  },
  wire: 100,
  wireBonus: 100,
  wireCost: 20,
  wireDrone: 0,
  wireDroneCost: 1e4,
};
